### ISSUE TITLE
playground-exec doesn't work under windows.

### ISSUE THREAD

**Issue by IraCasper** [grafov/go-playground#10]
windows CMD doesn't automatically expand *, and go run doesn't either, so M-x compile go run *.go doesn't work, giving this error

CreateFile *.go: The filename, directory name, or volume label syntax is incorrect.

which is the same as running go run *.go under CMD or Powershell. Though saving the file and then running  M-x eshell go run *.go works fine, of course, as a stopgap work around.

I suspect *.go needs to get expanded before being passed to M-x compile, or some other method used to run the playground.

**Comment by grafov** [comment]
I have no Windows machines around but I would like to accept the fix for this case tested under Windows OS.

**Comment by fractalbach** [comment]
just got package, using on Windows 10, ran into a similar issue with **Control-Return:**
~~~
go run *.go
CreateFile *.go: The filename, directory name, or volume label syntax is incorrect.

Compilation exited abnormally with code 1 at Sun Jul 15 01:16:59
~~~

Using **M-x go-run** works fine for me:
~~~
go run "c:/Users/Me/go/src/playground/at-2018-07-15-011948/snippet.go"
Results:

Compilation finished at Sun Jul 15 01:20:07
~~~


---

Regarding the error, which I had never  seen before, I google'd and found 
https://msdn.microsoft.com/en-us/library/ms832054.aspx which reads,

> Error Message:
> The filename, directory name, or volume label syntax is incorrect.
> 
> Explanation:
> The system does not accept the keyboard combination Alt+0 through Alt+32 or the following characters: \\ \\ / [ ] : | < > + ; = . ? "
> 
> User Action:
> Correct the file name or volume label and try the command again.

Also found a github issue, not sure if it's related or not, but it also produced the same message:
https://github.com/neovim/neovim/issues/6329
but it seems to have some good info.

**Comment by fractalbach** [comment]
I'm pretty new to emacs and haven't quite learned how emacs-lisp and the packages work, but I looked at
https://github.com/grafov/go-playground/blob/559d53bbc507394aaca3683325d17286637bf4f0/go-playground.el#L96

and then just tried **M-x compile**, and it auto-filled the buffer at the bottom of the screen with
`Compile command: go run "c:/Users/Me/go/src/playground/at-2018-07-15-011948/snippet.go"`
which also resulted in success:
~~~
go run "c:/Users/Me/go/src/playground/at-2018-07-15-011948/snippet.go"
Results:

Compilation finished at Sun Jul 15 01:42:50
~~~

**Comment by grafov** [comment]
I have added the option to pass arguments to the compiler instead of hardcoded "run *.go". So you could try customize the `go-command-args` variable. Could it work if you are set it for example to `run snippet.go`?

**Comment by ayrtoncarlos** [comment]
I use the `go run ./` command to run all files in the folder

and I use the `go run ./...` command to run all files in this folder and subsequent folders.

I hope I helped solve the problem. ;)

**Comment by grafov** [comment]
Thank you @ayrtoncarlos, `go run ./` looks like a reasonable variant. I'll add it as a default. Though it could be better to check it under Windows.

**Comment by grafov** [comment]
The solution by @vconcat merged, hope it helps.
