### ISSUE TITLE
What font are you using?

### ISSUE THREAD

**Issue by super-tomcat** [grafov/go-playground#13]
Hello, just wondered what font you are using in this image? thanks

https://github.com/grafov/go-playground/blob/master/playground-screenshot.png

**Comment by grafov** [comment]
I changed my font and settings for Emacs since the time of this screenshot. But it looks like the Monoid font: https://larsenwork.com/monoid/ If you liked this style of the monospace font I could recommend you look at Inconsolata, DejaVu Sans Mono and Anonymous Pro.

**Comment by super-tomcat** [comment]
Okay, thanks, I will give them a try 👍
